# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.7.4
      uses: actions/setup-python@v3
      with:
        python-version: "3.7.4"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install libewf
      run: |
        sudo apt-get update
        sudo apt-get install -y libewf-dev
    - name: Install PyInstaller
      run: |
        pip install pyinstaller
    - name: Build Windows executable
      run: |
        pyinstaller --onefile --name hiveEx.1.0 --icon ./icon/icon.ico ./src/main/main.py
    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: hiveEx.1.0
        path: dist/main.exe
